{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "1cb749a4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "<!DOCTYPE html>\n",
       "<html lang=\"en\">\n",
       "<head>\n",
       "    <meta charset=\"UTF-8\">\n",
       "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
       "    <title>Student Info Portal - Stylized</title>\n",
       "    <style>\n",
       "        /* BASE STYLES */\n",
       "        body { \n",
       "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n",
       "            margin: 0;\n",
       "            padding: 0;\n",
       "            background-color: #f4f4f9;\n",
       "            color: #333;\n",
       "            display: flex;\n",
       "            flex-direction: column;\n",
       "            min-height: 100vh; /* <-- LINE 17 in the Python string (Safe as string) */\n",
       "        }\n",
       "\n",
       "        /* HEADER STYLES */\n",
       "        header { background-color: #004080; color: white; padding: 20px; text-align: center; }\n",
       "\n",
       "        /* NAVIGATION BAR - RESPONSIVE STYLES */\n",
       "        .nav-menu { list-style: none; padding: 0; margin: 0; background-color: #0056b3; display: flex; justify-content: center; }\n",
       "        .nav-menu li a { display: block; color: white; text-decoration: none; padding: 15px 20px; transition: background-color 0.3s; }\n",
       "        .nav-menu li a:hover { background-color: #007bff; }\n",
       "        @media (max-width: 768px) { \n",
       "            .nav-menu { flex-direction: column; } \n",
       "            .nav-menu li { border-bottom: 1px solid #004080; } \n",
       "            .nav-menu li:last-child { border-bottom: none; }\n",
       "        }\n",
       "\n",
       "        /* MAIN CONTENT SECTION - CENTERED */\n",
       "        .content-container { \n",
       "            flex: 1; padding: 20px; max-width: 1000px; \n",
       "            margin: 20px auto; /* CENTERS the block horizontally */\n",
       "            background-color: white; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); \n",
       "        }\n",
       "        \n",
       "        /* FOOTER STYLES - Light Gray Background */\n",
       "        footer { background-color: #e0e0e0; color: #555; text-align: center; padding: 15px; margin-top: auto; }\n",
       "    </style>\n",
       "</head>\n",
       "<body>\n",
       "\n",
       "    <header><h1>Student Information Portal</h1></header>\n",
       "\n",
       "    <nav><ul class=\"nav-menu\">\n",
       "        <li><a href=\"#\">Home</a></li>\n",
       "        <li><a href=\"#\">Dashboard</a></li>\n",
       "        <li><a href=\"#\">Grades</a></li>\n",
       "        <li><a href=\"#\">Schedule</a></li>\n",
       "    </ul></nav>\n",
       "\n",
       "    <main class=\"content-container\">\n",
       "        <h2>Welcome Student!</h2>\n",
       "        <p>This content is centered and responsive. Resize your browser window to see the navigation menu become vertical.</p>\n",
       "        <button onclick=\"alert('Accessing dashboard...')\">Login</button>\n",
       "    </main>\n",
       "\n",
       "    <footer>\n",
       "        <p>&copy; 2025 Student Info Portal. All rights reserved.</p>\n",
       "    </footer>\n",
       "\n",
       "    <script>\n",
       "        function runSuccess() {\n",
       "            console.log(\"Script executed successfully.\");\n",
       "        }\n",
       "        runSuccess();\n",
       "    </script>\n",
       "</body>\n",
       "</html>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "from IPython.display import HTML, display\n",
    "\n",
    "# 1. Define the HTML content as a multiline Python string (using triple quotes)\n",
    "# This content contains the responsive CSS and structure you requested.\n",
    "HTML_CONTENT = \"\"\"\n",
    "<!DOCTYPE html>\n",
    "<html lang=\"en\">\n",
    "<head>\n",
    "    <meta charset=\"UTF-8\">\n",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
    "    <title>Student Info Portal - Stylized</title>\n",
    "    <style>\n",
    "        /* BASE STYLES */\n",
    "        body { \n",
    "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n",
    "            margin: 0;\n",
    "            padding: 0;\n",
    "            background-color: #f4f4f9;\n",
    "            color: #333;\n",
    "            display: flex;\n",
    "            flex-direction: column;\n",
    "            min-height: 100vh; /* <-- LINE 17 in the Python string (Safe as string) */\n",
    "        }\n",
    "\n",
    "        /* HEADER STYLES */\n",
    "        header { background-color: #004080; color: white; padding: 20px; text-align: center; }\n",
    "\n",
    "        /* NAVIGATION BAR - RESPONSIVE STYLES */\n",
    "        .nav-menu { list-style: none; padding: 0; margin: 0; background-color: #0056b3; display: flex; justify-content: center; }\n",
    "        .nav-menu li a { display: block; color: white; text-decoration: none; padding: 15px 20px; transition: background-color 0.3s; }\n",
    "        .nav-menu li a:hover { background-color: #007bff; }\n",
    "        @media (max-width: 768px) { \n",
    "            .nav-menu { flex-direction: column; } \n",
    "            .nav-menu li { border-bottom: 1px solid #004080; } \n",
    "            .nav-menu li:last-child { border-bottom: none; }\n",
    "        }\n",
    "\n",
    "        /* MAIN CONTENT SECTION - CENTERED */\n",
    "        .content-container { \n",
    "            flex: 1; padding: 20px; max-width: 1000px; \n",
    "            margin: 20px auto; /* CENTERS the block horizontally */\n",
    "            background-color: white; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); \n",
    "        }\n",
    "        \n",
    "        /* FOOTER STYLES - Light Gray Background */\n",
    "        footer { background-color: #e0e0e0; color: #555; text-align: center; padding: 15px; margin-top: auto; }\n",
    "    </style>\n",
    "</head>\n",
    "<body>\n",
    "\n",
    "    <header><h1>Student Information Portal</h1></header>\n",
    "\n",
    "    <nav><ul class=\"nav-menu\">\n",
    "        <li><a href=\"#\">Home</a></li>\n",
    "        <li><a href=\"#\">Dashboard</a></li>\n",
    "        <li><a href=\"#\">Grades</a></li>\n",
    "        <li><a href=\"#\">Schedule</a></li>\n",
    "    </ul></nav>\n",
    "\n",
    "    <main class=\"content-container\">\n",
    "        <h2>Welcome Student!</h2>\n",
    "        <p>This content is centered and responsive. Resize your browser window to see the navigation menu become vertical.</p>\n",
    "        <button onclick=\"alert('Accessing dashboard...')\">Login</button>\n",
    "    </main>\n",
    "\n",
    "    <footer>\n",
    "        <p>&copy; 2025 Student Info Portal. All rights reserved.</p>\n",
    "    </footer>\n",
    "\n",
    "    <script>\n",
    "        function runSuccess() {\n",
    "            console.log(\"Script executed successfully.\");\n",
    "        }\n",
    "        runSuccess();\n",
    "    </script>\n",
    "</body>\n",
    "</html>\n",
    "\"\"\"\n",
    "\n",
    "# 2. Use display(HTML(string)) to render the string as an HTML document.\n",
    "display(HTML(HTML_CONTENT))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "60d8d3ac",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "<!DOCTYPE html>\n",
       "<html lang=\"en\">\n",
       "<head>\n",
       "    <meta charset=\"UTF-8\">\n",
       "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
       "    <title>Student Info Portal - Stylized</title>\n",
       "    <style>\n",
       "        /* Base and Header styles */\n",
       "        body { \n",
       "            font-family: sans-serif; \n",
       "            margin: 0; \n",
       "            padding: 0; \n",
       "            background-color: #f4f4f9; \n",
       "            display: flex; \n",
       "            flex-direction: column; \n",
       "            min-height: 100vh; /* CSS unit 'vh' is safe inside a string */\n",
       "        }\n",
       "        header { background-color: #004080; color: white; padding: 20px; text-align: center; }\n",
       "\n",
       "        /* Responsive Navigation Bar */\n",
       "        .nav-menu { list-style: none; padding: 0; margin: 0; background-color: #0056b3; display: flex; justify-content: center; }\n",
       "        .nav-menu li a { display: block; color: white; text-decoration: none; padding: 15px 20px; transition: background-color 0.3s; }\n",
       "        .nav-menu li a:hover { background-color: #007bff; }\n",
       "        @media (max-width: 768px) { \n",
       "            .nav-menu { flex-direction: column; } \n",
       "            .nav-menu li { text-align: center; border-bottom: 1px solid #004080; } \n",
       "            .nav-menu li:last-child { border-bottom: none; } \n",
       "        }\n",
       "\n",
       "        /* Centered Content Section */\n",
       "        .content-container { \n",
       "            flex: 1; padding: 20px; max-width: 1000px; \n",
       "            margin: 20px auto; /* Centers the block horizontally */\n",
       "            background-color: white; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); \n",
       "        }\n",
       "        \n",
       "        /* Footer with light gray background */\n",
       "        footer { background-color: #e0e0e0; color: #555; text-align: center; padding: 15px; margin-top: auto; }\n",
       "    </style>\n",
       "</head>\n",
       "<body>\n",
       "    <header><h1>Student Information Portal</h1></header>\n",
       "    <nav><ul class=\"nav-menu\">\n",
       "        <li><a href=\"#\">Home</a></li><li><a href=\"#\">Dashboard</a></li>\n",
       "        <li><a href=\"#\">Grades</a></li><li><a href=\"#\">Schedule</a></li>\n",
       "    </ul></nav>\n",
       "    <main class=\"content-container\">\n",
       "        <h2>Welcome Student!</h2>\n",
       "        <p>This content is centered and responsive.</p>\n",
       "        <button onclick=\"alert('Accessing dashboard...')\">Login</button>\n",
       "    </main>\n",
       "    <footer><p>&copy; 2025 Student Info Portal. All rights reserved.</p></footer>\n",
       "</body>\n",
       "</html>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "✅ Success: HTML file 'portal_homepage.html' created and rendered above.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "# Import the necessary function for displaying HTML in Jupyter\n",
    "from IPython.display import HTML, display\n",
    "\n",
    "# Store the complete HTML code in a multi-line string variable\n",
    "# This code includes the responsive nav, centered content, and light gray footer.\n",
    "HTML_CONTENT = \"\"\"\n",
    "<!DOCTYPE html>\n",
    "<html lang=\"en\">\n",
    "<head>\n",
    "    <meta charset=\"UTF-8\">\n",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
    "    <title>Student Info Portal - Stylized</title>\n",
    "    <style>\n",
    "        /* Base and Header styles */\n",
    "        body { \n",
    "            font-family: sans-serif; \n",
    "            margin: 0; \n",
    "            padding: 0; \n",
    "            background-color: #f4f4f9; \n",
    "            display: flex; \n",
    "            flex-direction: column; \n",
    "            min-height: 100vh; /* CSS unit 'vh' is safe inside a string */\n",
    "        }\n",
    "        header { background-color: #004080; color: white; padding: 20px; text-align: center; }\n",
    "\n",
    "        /* Responsive Navigation Bar */\n",
    "        .nav-menu { list-style: none; padding: 0; margin: 0; background-color: #0056b3; display: flex; justify-content: center; }\n",
    "        .nav-menu li a { display: block; color: white; text-decoration: none; padding: 15px 20px; transition: background-color 0.3s; }\n",
    "        .nav-menu li a:hover { background-color: #007bff; }\n",
    "        @media (max-width: 768px) { \n",
    "            .nav-menu { flex-direction: column; } \n",
    "            .nav-menu li { text-align: center; border-bottom: 1px solid #004080; } \n",
    "            .nav-menu li:last-child { border-bottom: none; } \n",
    "        }\n",
    "\n",
    "        /* Centered Content Section */\n",
    "        .content-container { \n",
    "            flex: 1; padding: 20px; max-width: 1000px; \n",
    "            margin: 20px auto; /* Centers the block horizontally */\n",
    "            background-color: white; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); \n",
    "        }\n",
    "        \n",
    "        /* Footer with light gray background */\n",
    "        footer { background-color: #e0e0e0; color: #555; text-align: center; padding: 15px; margin-top: auto; }\n",
    "    </style>\n",
    "</head>\n",
    "<body>\n",
    "    <header><h1>Student Information Portal</h1></header>\n",
    "    <nav><ul class=\"nav-menu\">\n",
    "        <li><a href=\"#\">Home</a></li><li><a href=\"#\">Dashboard</a></li>\n",
    "        <li><a href=\"#\">Grades</a></li><li><a href=\"#\">Schedule</a></li>\n",
    "    </ul></nav>\n",
    "    <main class=\"content-container\">\n",
    "        <h2>Welcome Student!</h2>\n",
    "        <p>This content is centered and responsive.</p>\n",
    "        <button onclick=\"alert('Accessing dashboard...')\">Login</button>\n",
    "    </main>\n",
    "    <footer><p>&copy; 2025 Student Info Portal. All rights reserved.</p></footer>\n",
    "</body>\n",
    "</html>\n",
    "\"\"\"\n",
    "\n",
    "FILE_NAME = \"portal_homepage.html\"\n",
    "\n",
    "try:\n",
    "    # 'with open(...)' ensures the file is closed automatically.\n",
    "    with open(FILE_NAME, 'w', encoding='utf-8') as f:\n",
    "        f.write(HTML_CONTENT)\n",
    "    \n",
    "    # Renders the HTML directly in the Jupyter Notebook cell for preview\n",
    "    display(HTML(HTML_CONTENT))\n",
    "    \n",
    "    # Check if the file was created successfully and print a success message\n",
    "    if os.path.exists(FILE_NAME):\n",
    "        print(f\"\\n✅ Success: HTML file '{FILE_NAME}' created and rendered above.\")\n",
    "    else:\n",
    "        print(f\"\\n❌ Error: File '{FILE_NAME}' was not created.\")\n",
    "\n",
    "except IOError as e:\n",
    "    # Handles errors that occur during file writing \n",
    "    print(f\"\\n❌ An IOError occurred while writing the file: {e}\")\n",
    "except Exception as e:\n",
    "    # Handles any other unexpected errors\n",
    "    print(f\"\\n❌ An unexpected error occurred: {e}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
