{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "badb7baa",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "<!DOCTYPE html>\n",
       "<html lang=\"en\">\n",
       "<head>\n",
       "    <meta charset=\"UTF-8\">\n",
       "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
       "    <title>Login Validation</title>\n",
       "    <style>\n",
       "        body {\n",
       "            font-family: Arial, sans-serif;\n",
       "            background-color: #f4f4f9;\n",
       "            display: flex;\n",
       "            justify-content: center;\n",
       "            align-items: center;\n",
       "            /* Using a fixed height here to ensure rendering in a small Jupyter output area */\n",
       "            margin: 0; \n",
       "        }\n",
       "        .login-container {\n",
       "            background-color: white;\n",
       "            padding: 30px;\n",
       "            border-radius: 8px;\n",
       "            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\n",
       "            width: 300px;\n",
       "        }\n",
       "        h2 { text-align: center; color: #333; margin-bottom: 20px; }\n",
       "        .form-group { margin-bottom: 15px; }\n",
       "        label { display: block; margin-bottom: 5px; font-weight: bold; }\n",
       "        input[type=\"text\"], input[type=\"password\"] {\n",
       "            width: 100%;\n",
       "            padding: 10px;\n",
       "            border: 1px solid #ccc;\n",
       "            border-radius: 4px;\n",
       "            box-sizing: border-box;\n",
       "        }\n",
       "        button {\n",
       "            width: 100%;\n",
       "            padding: 10px;\n",
       "            background-color: #0056b3;\n",
       "            color: white;\n",
       "            border: none;\n",
       "            border-radius: 4px;\n",
       "            cursor: pointer;\n",
       "            font-size: 1em;\n",
       "            transition: background-color 0.3s;\n",
       "        }\n",
       "        button:hover { background-color: #004080; }\n",
       "        .error-message {\n",
       "            color: red;\n",
       "            font-size: 0.9em;\n",
       "            margin-top: 5px;\n",
       "            display: none; /* Initially hidden */\n",
       "        }\n",
       "    </style>\n",
       "</head>\n",
       "<body>\n",
       "\n",
       "    <div class=\"login-container\">\n",
       "        <h2>Student Login</h2>\n",
       "        <form id=\"loginForm\" onsubmit=\"return validateForm()\">\n",
       "            \n",
       "            <div class=\"form-group\">\n",
       "                <label for=\"username\">Username:</label>\n",
       "                <input type=\"text\" id=\"username\" name=\"username\">\n",
       "                <div id=\"username-error\" class=\"error-message\">Username is required.</div>\n",
       "            </div>\n",
       "\n",
       "            <div class=\"form-group\">\n",
       "                <label for=\"password\">Password:</label>\n",
       "                <input type=\"password\" id=\"password\" name=\"password\">\n",
       "                <div id=\"password-error\" class=\"error-message\">Password is required.</div>\n",
       "            </div>\n",
       "\n",
       "            <button type=\"submit\">Log In</button>\n",
       "        </form>\n",
       "    </div>\n",
       "\n",
       "    <script>\n",
       "        function validateForm() {\n",
       "            const username = document.getElementById('username').value.trim();\n",
       "            const password = document.getElementById('password').value.trim();\n",
       "            \n",
       "            const usernameError = document.getElementById('username-error');\n",
       "            const passwordError = document.getElementById('password-error');\n",
       "\n",
       "            let isValid = true; \n",
       "\n",
       "            // Clear previous errors\n",
       "            usernameError.style.display = 'none';\n",
       "            passwordError.style.display = 'none';\n",
       "\n",
       "            // Validate Username\n",
       "            if (username === \"\") {\n",
       "                usernameError.style.display = 'block'; // Show error\n",
       "                isValid = false;\n",
       "            }\n",
       "\n",
       "            // Validate Password\n",
       "            if (password === \"\") {\n",
       "                passwordError.style.display = 'block'; // Show error\n",
       "                isValid = false;\n",
       "            }\n",
       "\n",
       "            if (isValid) {\n",
       "                // If valid, show success message and prevent real form submission for demonstration\n",
       "                alert('Validation successful! (Form submission prevented for demo.)');\n",
       "            } \n",
       "            \n",
       "            return false; // Always return false to prevent Jupyter cell reload\n",
       "        }\n",
       "    </script>\n",
       "</body>\n",
       "</html>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "from IPython.display import HTML, display\n",
    "\n",
    "# Store the complete HTML/CSS/JS code as a Python string\n",
    "HTML_CONTENT = \"\"\"\n",
    "<!DOCTYPE html>\n",
    "<html lang=\"en\">\n",
    "<head>\n",
    "    <meta charset=\"UTF-8\">\n",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
    "    <title>Login Validation</title>\n",
    "    <style>\n",
    "        body {\n",
    "            font-family: Arial, sans-serif;\n",
    "            background-color: #f4f4f9;\n",
    "            display: flex;\n",
    "            justify-content: center;\n",
    "            align-items: center;\n",
    "            /* Using a fixed height here to ensure rendering in a small Jupyter output area */\n",
    "            margin: 0; \n",
    "        }\n",
    "        .login-container {\n",
    "            background-color: white;\n",
    "            padding: 30px;\n",
    "            border-radius: 8px;\n",
    "            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\n",
    "            width: 300px;\n",
    "        }\n",
    "        h2 { text-align: center; color: #333; margin-bottom: 20px; }\n",
    "        .form-group { margin-bottom: 15px; }\n",
    "        label { display: block; margin-bottom: 5px; font-weight: bold; }\n",
    "        input[type=\"text\"], input[type=\"password\"] {\n",
    "            width: 100%;\n",
    "            padding: 10px;\n",
    "            border: 1px solid #ccc;\n",
    "            border-radius: 4px;\n",
    "            box-sizing: border-box;\n",
    "        }\n",
    "        button {\n",
    "            width: 100%;\n",
    "            padding: 10px;\n",
    "            background-color: #0056b3;\n",
    "            color: white;\n",
    "            border: none;\n",
    "            border-radius: 4px;\n",
    "            cursor: pointer;\n",
    "            font-size: 1em;\n",
    "            transition: background-color 0.3s;\n",
    "        }\n",
    "        button:hover { background-color: #004080; }\n",
    "        .error-message {\n",
    "            color: red;\n",
    "            font-size: 0.9em;\n",
    "            margin-top: 5px;\n",
    "            display: none; /* Initially hidden */\n",
    "        }\n",
    "    </style>\n",
    "</head>\n",
    "<body>\n",
    "\n",
    "    <div class=\"login-container\">\n",
    "        <h2>Student Login</h2>\n",
    "        <form id=\"loginForm\" onsubmit=\"return validateForm()\">\n",
    "            \n",
    "            <div class=\"form-group\">\n",
    "                <label for=\"username\">Username:</label>\n",
    "                <input type=\"text\" id=\"username\" name=\"username\">\n",
    "                <div id=\"username-error\" class=\"error-message\">Username is required.</div>\n",
    "            </div>\n",
    "\n",
    "            <div class=\"form-group\">\n",
    "                <label for=\"password\">Password:</label>\n",
    "                <input type=\"password\" id=\"password\" name=\"password\">\n",
    "                <div id=\"password-error\" class=\"error-message\">Password is required.</div>\n",
    "            </div>\n",
    "\n",
    "            <button type=\"submit\">Log In</button>\n",
    "        </form>\n",
    "    </div>\n",
    "\n",
    "    <script>\n",
    "        function validateForm() {\n",
    "            const username = document.getElementById('username').value.trim();\n",
    "            const password = document.getElementById('password').value.trim();\n",
    "            \n",
    "            const usernameError = document.getElementById('username-error');\n",
    "            const passwordError = document.getElementById('password-error');\n",
    "\n",
    "            let isValid = true; \n",
    "\n",
    "            // Clear previous errors\n",
    "            usernameError.style.display = 'none';\n",
    "            passwordError.style.display = 'none';\n",
    "\n",
    "            // Validate Username\n",
    "            if (username === \"\") {\n",
    "                usernameError.style.display = 'block'; // Show error\n",
    "                isValid = false;\n",
    "            }\n",
    "\n",
    "            // Validate Password\n",
    "            if (password === \"\") {\n",
    "                passwordError.style.display = 'block'; // Show error\n",
    "                isValid = false;\n",
    "            }\n",
    "\n",
    "            if (isValid) {\n",
    "                // If valid, show success message and prevent real form submission for demonstration\n",
    "                alert('Validation successful! (Form submission prevented for demo.)');\n",
    "            } \n",
    "            \n",
    "            return false; // Always return false to prevent Jupyter cell reload\n",
    "        }\n",
    "    </script>\n",
    "</body>\n",
    "</html>\n",
    "\"\"\"\n",
    "\n",
    "# The essential step for running HTML/CSS/JS code in Jupyter:\n",
    "display(HTML(HTML_CONTENT))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
